### ISSUE TITLE
Malformed header "content-type"

### ISSUE THREAD

**Issue by romaincazier** [ryancramerdesign/PageEditRestore#1]
My server was reporting 500 errors with the message `headers: malformed header 'content-type'`. Looking at the access log I quickly noticed it was coming from the ping and indeed on [line 133](https://github.com/ryancramerdesign/PageEditRestore/blob/db0a7714ce9abe43776bafb045c880806ce969ec/PageEditRestore.module#L133) the header is set but with PW’s syntax rather than PHP’s.

It should be `header('Content-Type: application/json')`

Habits I guess :-)

(and thanks for this valuable module)

**Comment by ryancramerdesign** [comment]
Oops, thanks @romaincazier I've pushed a fix for this.
